//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDS.ServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRef.ServicioWebSoap")]
    public interface ServicioWebSoap {
        
        // CODEGEN: Generating message contract since element name j1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Parametros", ReplyAction="*")]
        EDDS.ServiceRef.ParametrosResponse Parametros(EDDS.ServiceRef.ParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Parametros", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.ParametrosResponse> ParametrosAsync(EDDS.ServiceRef.ParametrosRequest request);
        
        // CODEGEN: Generating message contract since element name RetJugador1Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetJugador1", ReplyAction="*")]
        EDDS.ServiceRef.RetJugador1Response RetJugador1(EDDS.ServiceRef.RetJugador1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetJugador1", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.RetJugador1Response> RetJugador1Async(EDDS.ServiceRef.RetJugador1Request request);
        
        // CODEGEN: Generating message contract since element name RetJugador2Result from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetJugador2", ReplyAction="*")]
        EDDS.ServiceRef.RetJugador2Response RetJugador2(EDDS.ServiceRef.RetJugador2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetJugador2", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.RetJugador2Response> RetJugador2Async(EDDS.ServiceRef.RetJugador2Request request);
        
        // CODEGEN: Generating message contract since element name RetTamanoXResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetTamanoX", ReplyAction="*")]
        EDDS.ServiceRef.RetTamanoXResponse RetTamanoX(EDDS.ServiceRef.RetTamanoXRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetTamanoX", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.RetTamanoXResponse> RetTamanoXAsync(EDDS.ServiceRef.RetTamanoXRequest request);
        
        // CODEGEN: Generating message contract since element name RetTamanoYResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetTamanoY", ReplyAction="*")]
        EDDS.ServiceRef.RetTamanoYResponse RetTamanoY(EDDS.ServiceRef.RetTamanoYRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetTamanoY", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.RetTamanoYResponse> RetTamanoYAsync(EDDS.ServiceRef.RetTamanoYRequest request);
        
        // CODEGEN: Generating message contract since element name RetTipoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetTipo", ReplyAction="*")]
        EDDS.ServiceRef.RetTipoResponse RetTipo(EDDS.ServiceRef.RetTipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetTipo", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.RetTipoResponse> RetTipoAsync(EDDS.ServiceRef.RetTipoRequest request);
        
        // CODEGEN: Generating message contract since element name RetTiempoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetTiempo", ReplyAction="*")]
        EDDS.ServiceRef.RetTiempoResponse RetTiempo(EDDS.ServiceRef.RetTiempoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetTiempo", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.RetTiempoResponse> RetTiempoAsync(EDDS.ServiceRef.RetTiempoRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        EDDS.ServiceRef.HelloWorldResponse HelloWorld(EDDS.ServiceRef.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.HelloWorldResponse> HelloWorldAsync(EDDS.ServiceRef.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name Us from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsercionMasivaArbol", ReplyAction="*")]
        EDDS.ServiceRef.InsercionMasivaArbolResponse InsercionMasivaArbol(EDDS.ServiceRef.InsercionMasivaArbolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsercionMasivaArbol", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.InsercionMasivaArbolResponse> InsercionMasivaArbolAsync(EDDS.ServiceRef.InsercionMasivaArbolRequest request);
        
        // CODEGEN: Generating message contract since element name UsB from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsercionMasivaListasDelArbol", ReplyAction="*")]
        EDDS.ServiceRef.InsercionMasivaListasDelArbolResponse InsercionMasivaListasDelArbol(EDDS.ServiceRef.InsercionMasivaListasDelArbolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsercionMasivaListasDelArbol", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.InsercionMasivaListasDelArbolResponse> InsercionMasivaListasDelArbolAsync(EDDS.ServiceRef.InsercionMasivaListasDelArbolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pintar", ReplyAction="*")]
        void Pintar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pintar", ReplyAction="*")]
        System.Threading.Tasks.Task PintarAsync();
        
        // CODEGEN: Generating message contract since element name nickn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarEnArbol", ReplyAction="*")]
        EDDS.ServiceRef.EliminarEnArbolResponse EliminarEnArbol(EDDS.ServiceRef.EliminarEnArbolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarEnArbol", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.EliminarEnArbolResponse> EliminarEnArbolAsync(EDDS.ServiceRef.EliminarEnArbolRequest request);
        
        // CODEGEN: Generating message contract since element name Ant from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarEnArbol", ReplyAction="*")]
        EDDS.ServiceRef.ModificarEnArbolResponse ModificarEnArbol(EDDS.ServiceRef.ModificarEnArbolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarEnArbol", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.ModificarEnArbolResponse> ModificarEnArbolAsync(EDDS.ServiceRef.ModificarEnArbolRequest request);
        
        // CODEGEN: Generating message contract since element name jug from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IncertarEnMatrizLive", ReplyAction="*")]
        EDDS.ServiceRef.IncertarEnMatrizLiveResponse IncertarEnMatrizLive(EDDS.ServiceRef.IncertarEnMatrizLiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IncertarEnMatrizLive", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.IncertarEnMatrizLiveResponse> IncertarEnMatrizLiveAsync(EDDS.ServiceRef.IncertarEnMatrizLiveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PintarMSobrevivientes", ReplyAction="*")]
        void PintarMSobrevivientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PintarMSobrevivientes", ReplyAction="*")]
        System.Threading.Tasks.Task PintarMSobrevivientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PintarMDestruidas", ReplyAction="*")]
        void PintarMDestruidas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PintarMDestruidas", ReplyAction="*")]
        System.Threading.Tasks.Task PintarMDestruidasAsync();
        
        // CODEGEN: Generating message contract since element name jug from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarEnMatriz", ReplyAction="*")]
        EDDS.ServiceRef.EliminarEnMatrizResponse EliminarEnMatriz(EDDS.ServiceRef.EliminarEnMatrizRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarEnMatriz", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.EliminarEnMatrizResponse> EliminarEnMatrizAsync(EDDS.ServiceRef.EliminarEnMatrizRequest request);
        
        // CODEGEN: Generating message contract since element name r from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CopiarImagenes", ReplyAction="*")]
        EDDS.ServiceRef.CopiarImagenesResponse CopiarImagenes(EDDS.ServiceRef.CopiarImagenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CopiarImagenes", ReplyAction="*")]
        System.Threading.Tasks.Task<EDDS.ServiceRef.CopiarImagenesResponse> CopiarImagenesAsync(EDDS.ServiceRef.CopiarImagenesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParametrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Parametros", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.ParametrosRequestBody Body;
        
        public ParametrosRequest() {
        }
        
        public ParametrosRequest(EDDS.ServiceRef.ParametrosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParametrosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string j1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string j2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nn1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nn2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string nn3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string nn4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string tx;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ty;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string tip;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string tim;
        
        public ParametrosRequestBody() {
        }
        
        public ParametrosRequestBody(string j1, string j2, string nn1, string nn2, string nn3, string nn4, string tx, string ty, string tip, string tim) {
            this.j1 = j1;
            this.j2 = j2;
            this.nn1 = nn1;
            this.nn2 = nn2;
            this.nn3 = nn3;
            this.nn4 = nn4;
            this.tx = tx;
            this.ty = ty;
            this.tip = tip;
            this.tim = tim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParametrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParametrosResponse", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.ParametrosResponseBody Body;
        
        public ParametrosResponse() {
        }
        
        public ParametrosResponse(EDDS.ServiceRef.ParametrosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ParametrosResponseBody {
        
        public ParametrosResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetJugador1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetJugador1", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.RetJugador1RequestBody Body;
        
        public RetJugador1Request() {
        }
        
        public RetJugador1Request(EDDS.ServiceRef.RetJugador1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetJugador1RequestBody {
        
        public RetJugador1RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetJugador1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetJugador1Response", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.RetJugador1ResponseBody Body;
        
        public RetJugador1Response() {
        }
        
        public RetJugador1Response(EDDS.ServiceRef.RetJugador1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetJugador1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetJugador1Result;
        
        public RetJugador1ResponseBody() {
        }
        
        public RetJugador1ResponseBody(string RetJugador1Result) {
            this.RetJugador1Result = RetJugador1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetJugador2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetJugador2", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.RetJugador2RequestBody Body;
        
        public RetJugador2Request() {
        }
        
        public RetJugador2Request(EDDS.ServiceRef.RetJugador2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetJugador2RequestBody {
        
        public RetJugador2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetJugador2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetJugador2Response", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.RetJugador2ResponseBody Body;
        
        public RetJugador2Response() {
        }
        
        public RetJugador2Response(EDDS.ServiceRef.RetJugador2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetJugador2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetJugador2Result;
        
        public RetJugador2ResponseBody() {
        }
        
        public RetJugador2ResponseBody(string RetJugador2Result) {
            this.RetJugador2Result = RetJugador2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetTamanoXRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetTamanoX", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.RetTamanoXRequestBody Body;
        
        public RetTamanoXRequest() {
        }
        
        public RetTamanoXRequest(EDDS.ServiceRef.RetTamanoXRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetTamanoXRequestBody {
        
        public RetTamanoXRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetTamanoXResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetTamanoXResponse", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.RetTamanoXResponseBody Body;
        
        public RetTamanoXResponse() {
        }
        
        public RetTamanoXResponse(EDDS.ServiceRef.RetTamanoXResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetTamanoXResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetTamanoXResult;
        
        public RetTamanoXResponseBody() {
        }
        
        public RetTamanoXResponseBody(string RetTamanoXResult) {
            this.RetTamanoXResult = RetTamanoXResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetTamanoYRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetTamanoY", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.RetTamanoYRequestBody Body;
        
        public RetTamanoYRequest() {
        }
        
        public RetTamanoYRequest(EDDS.ServiceRef.RetTamanoYRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetTamanoYRequestBody {
        
        public RetTamanoYRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetTamanoYResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetTamanoYResponse", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.RetTamanoYResponseBody Body;
        
        public RetTamanoYResponse() {
        }
        
        public RetTamanoYResponse(EDDS.ServiceRef.RetTamanoYResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetTamanoYResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetTamanoYResult;
        
        public RetTamanoYResponseBody() {
        }
        
        public RetTamanoYResponseBody(string RetTamanoYResult) {
            this.RetTamanoYResult = RetTamanoYResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetTipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetTipo", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.RetTipoRequestBody Body;
        
        public RetTipoRequest() {
        }
        
        public RetTipoRequest(EDDS.ServiceRef.RetTipoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetTipoRequestBody {
        
        public RetTipoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetTipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetTipoResponse", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.RetTipoResponseBody Body;
        
        public RetTipoResponse() {
        }
        
        public RetTipoResponse(EDDS.ServiceRef.RetTipoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetTipoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetTipoResult;
        
        public RetTipoResponseBody() {
        }
        
        public RetTipoResponseBody(string RetTipoResult) {
            this.RetTipoResult = RetTipoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetTiempoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetTiempo", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.RetTiempoRequestBody Body;
        
        public RetTiempoRequest() {
        }
        
        public RetTiempoRequest(EDDS.ServiceRef.RetTiempoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetTiempoRequestBody {
        
        public RetTiempoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetTiempoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetTiempoResponse", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.RetTiempoResponseBody Body;
        
        public RetTiempoResponse() {
        }
        
        public RetTiempoResponse(EDDS.ServiceRef.RetTiempoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetTiempoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetTiempoResult;
        
        public RetTiempoResponseBody() {
        }
        
        public RetTiempoResponseBody(string RetTiempoResult) {
            this.RetTiempoResult = RetTiempoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(EDDS.ServiceRef.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(EDDS.ServiceRef.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsercionMasivaArbolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsercionMasivaArbol", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.InsercionMasivaArbolRequestBody Body;
        
        public InsercionMasivaArbolRequest() {
        }
        
        public InsercionMasivaArbolRequest(EDDS.ServiceRef.InsercionMasivaArbolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsercionMasivaArbolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Us;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Cont;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Corr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int Logi;
        
        public InsercionMasivaArbolRequestBody() {
        }
        
        public InsercionMasivaArbolRequestBody(string Us, string Cont, string Corr, int Logi) {
            this.Us = Us;
            this.Cont = Cont;
            this.Corr = Corr;
            this.Logi = Logi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsercionMasivaArbolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsercionMasivaArbolResponse", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.InsercionMasivaArbolResponseBody Body;
        
        public InsercionMasivaArbolResponse() {
        }
        
        public InsercionMasivaArbolResponse(EDDS.ServiceRef.InsercionMasivaArbolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsercionMasivaArbolResponseBody {
        
        public InsercionMasivaArbolResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsercionMasivaListasDelArbolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsercionMasivaListasDelArbol", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.InsercionMasivaListasDelArbolRequestBody Body;
        
        public InsercionMasivaListasDelArbolRequest() {
        }
        
        public InsercionMasivaListasDelArbolRequest(EDDS.ServiceRef.InsercionMasivaListasDelArbolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsercionMasivaListasDelArbolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UsB;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Op;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int bb;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int dd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ee;
        
        public InsercionMasivaListasDelArbolRequestBody() {
        }
        
        public InsercionMasivaListasDelArbolRequestBody(string UsB, string Op, int bb, int cc, int dd, int ee) {
            this.UsB = UsB;
            this.Op = Op;
            this.bb = bb;
            this.cc = cc;
            this.dd = dd;
            this.ee = ee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsercionMasivaListasDelArbolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsercionMasivaListasDelArbolResponse", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.InsercionMasivaListasDelArbolResponseBody Body;
        
        public InsercionMasivaListasDelArbolResponse() {
        }
        
        public InsercionMasivaListasDelArbolResponse(EDDS.ServiceRef.InsercionMasivaListasDelArbolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsercionMasivaListasDelArbolResponseBody {
        
        public InsercionMasivaListasDelArbolResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarEnArbolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarEnArbol", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.EliminarEnArbolRequestBody Body;
        
        public EliminarEnArbolRequest() {
        }
        
        public EliminarEnArbolRequest(EDDS.ServiceRef.EliminarEnArbolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarEnArbolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickn;
        
        public EliminarEnArbolRequestBody() {
        }
        
        public EliminarEnArbolRequestBody(string nickn) {
            this.nickn = nickn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarEnArbolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarEnArbolResponse", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.EliminarEnArbolResponseBody Body;
        
        public EliminarEnArbolResponse() {
        }
        
        public EliminarEnArbolResponse(EDDS.ServiceRef.EliminarEnArbolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EliminarEnArbolResponseBody {
        
        public EliminarEnArbolResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarEnArbolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarEnArbol", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.ModificarEnArbolRequestBody Body;
        
        public ModificarEnArbolRequest() {
        }
        
        public ModificarEnArbolRequest(EDDS.ServiceRef.ModificarEnArbolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarEnArbolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ant;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Mail;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Log;
        
        public ModificarEnArbolRequestBody() {
        }
        
        public ModificarEnArbolRequestBody(string Ant, string Nick, string Pass, string Mail, int Log) {
            this.Ant = Ant;
            this.Nick = Nick;
            this.Pass = Pass;
            this.Mail = Mail;
            this.Log = Log;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarEnArbolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarEnArbolResponse", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.ModificarEnArbolResponseBody Body;
        
        public ModificarEnArbolResponse() {
        }
        
        public ModificarEnArbolResponse(EDDS.ServiceRef.ModificarEnArbolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModificarEnArbolResponseBody {
        
        public ModificarEnArbolResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IncertarEnMatrizLiveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IncertarEnMatrizLive", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.IncertarEnMatrizLiveRequestBody Body;
        
        public IncertarEnMatrizLiveRequest() {
        }
        
        public IncertarEnMatrizLiveRequest(EDDS.ServiceRef.IncertarEnMatrizLiveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IncertarEnMatrizLiveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jug;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int col;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int fil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string uni;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int des;
        
        public IncertarEnMatrizLiveRequestBody() {
        }
        
        public IncertarEnMatrizLiveRequestBody(string jug, int col, int fil, string uni, int des) {
            this.jug = jug;
            this.col = col;
            this.fil = fil;
            this.uni = uni;
            this.des = des;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IncertarEnMatrizLiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IncertarEnMatrizLiveResponse", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.IncertarEnMatrizLiveResponseBody Body;
        
        public IncertarEnMatrizLiveResponse() {
        }
        
        public IncertarEnMatrizLiveResponse(EDDS.ServiceRef.IncertarEnMatrizLiveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class IncertarEnMatrizLiveResponseBody {
        
        public IncertarEnMatrizLiveResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarEnMatrizRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarEnMatriz", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.EliminarEnMatrizRequestBody Body;
        
        public EliminarEnMatrizRequest() {
        }
        
        public EliminarEnMatrizRequest(EDDS.ServiceRef.EliminarEnMatrizRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarEnMatrizRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jug;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int col;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int fil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string uni;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int niv;
        
        public EliminarEnMatrizRequestBody() {
        }
        
        public EliminarEnMatrizRequestBody(string jug, int col, int fil, string uni, int niv) {
            this.jug = jug;
            this.col = col;
            this.fil = fil;
            this.uni = uni;
            this.niv = niv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarEnMatrizResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarEnMatrizResponse", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.EliminarEnMatrizResponseBody Body;
        
        public EliminarEnMatrizResponse() {
        }
        
        public EliminarEnMatrizResponse(EDDS.ServiceRef.EliminarEnMatrizResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EliminarEnMatrizResponseBody {
        
        public EliminarEnMatrizResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CopiarImagenesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CopiarImagenes", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.CopiarImagenesRequestBody Body;
        
        public CopiarImagenesRequest() {
        }
        
        public CopiarImagenesRequest(EDDS.ServiceRef.CopiarImagenesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CopiarImagenesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string r;
        
        public CopiarImagenesRequestBody() {
        }
        
        public CopiarImagenesRequestBody(string r) {
            this.r = r;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CopiarImagenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CopiarImagenesResponse", Namespace="http://tempuri.org/", Order=0)]
        public EDDS.ServiceRef.CopiarImagenesResponseBody Body;
        
        public CopiarImagenesResponse() {
        }
        
        public CopiarImagenesResponse(EDDS.ServiceRef.CopiarImagenesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CopiarImagenesResponseBody {
        
        public CopiarImagenesResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebSoapChannel : EDDS.ServiceRef.ServicioWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebSoapClient : System.ServiceModel.ClientBase<EDDS.ServiceRef.ServicioWebSoap>, EDDS.ServiceRef.ServicioWebSoap {
        
        public ServicioWebSoapClient() {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.ParametrosResponse EDDS.ServiceRef.ServicioWebSoap.Parametros(EDDS.ServiceRef.ParametrosRequest request) {
            return base.Channel.Parametros(request);
        }
        
        public void Parametros(string j1, string j2, string nn1, string nn2, string nn3, string nn4, string tx, string ty, string tip, string tim) {
            EDDS.ServiceRef.ParametrosRequest inValue = new EDDS.ServiceRef.ParametrosRequest();
            inValue.Body = new EDDS.ServiceRef.ParametrosRequestBody();
            inValue.Body.j1 = j1;
            inValue.Body.j2 = j2;
            inValue.Body.nn1 = nn1;
            inValue.Body.nn2 = nn2;
            inValue.Body.nn3 = nn3;
            inValue.Body.nn4 = nn4;
            inValue.Body.tx = tx;
            inValue.Body.ty = ty;
            inValue.Body.tip = tip;
            inValue.Body.tim = tim;
            EDDS.ServiceRef.ParametrosResponse retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).Parametros(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.ParametrosResponse> EDDS.ServiceRef.ServicioWebSoap.ParametrosAsync(EDDS.ServiceRef.ParametrosRequest request) {
            return base.Channel.ParametrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.ParametrosResponse> ParametrosAsync(string j1, string j2, string nn1, string nn2, string nn3, string nn4, string tx, string ty, string tip, string tim) {
            EDDS.ServiceRef.ParametrosRequest inValue = new EDDS.ServiceRef.ParametrosRequest();
            inValue.Body = new EDDS.ServiceRef.ParametrosRequestBody();
            inValue.Body.j1 = j1;
            inValue.Body.j2 = j2;
            inValue.Body.nn1 = nn1;
            inValue.Body.nn2 = nn2;
            inValue.Body.nn3 = nn3;
            inValue.Body.nn4 = nn4;
            inValue.Body.tx = tx;
            inValue.Body.ty = ty;
            inValue.Body.tip = tip;
            inValue.Body.tim = tim;
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).ParametrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.RetJugador1Response EDDS.ServiceRef.ServicioWebSoap.RetJugador1(EDDS.ServiceRef.RetJugador1Request request) {
            return base.Channel.RetJugador1(request);
        }
        
        public string RetJugador1() {
            EDDS.ServiceRef.RetJugador1Request inValue = new EDDS.ServiceRef.RetJugador1Request();
            inValue.Body = new EDDS.ServiceRef.RetJugador1RequestBody();
            EDDS.ServiceRef.RetJugador1Response retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).RetJugador1(inValue);
            return retVal.Body.RetJugador1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.RetJugador1Response> EDDS.ServiceRef.ServicioWebSoap.RetJugador1Async(EDDS.ServiceRef.RetJugador1Request request) {
            return base.Channel.RetJugador1Async(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.RetJugador1Response> RetJugador1Async() {
            EDDS.ServiceRef.RetJugador1Request inValue = new EDDS.ServiceRef.RetJugador1Request();
            inValue.Body = new EDDS.ServiceRef.RetJugador1RequestBody();
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).RetJugador1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.RetJugador2Response EDDS.ServiceRef.ServicioWebSoap.RetJugador2(EDDS.ServiceRef.RetJugador2Request request) {
            return base.Channel.RetJugador2(request);
        }
        
        public string RetJugador2() {
            EDDS.ServiceRef.RetJugador2Request inValue = new EDDS.ServiceRef.RetJugador2Request();
            inValue.Body = new EDDS.ServiceRef.RetJugador2RequestBody();
            EDDS.ServiceRef.RetJugador2Response retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).RetJugador2(inValue);
            return retVal.Body.RetJugador2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.RetJugador2Response> EDDS.ServiceRef.ServicioWebSoap.RetJugador2Async(EDDS.ServiceRef.RetJugador2Request request) {
            return base.Channel.RetJugador2Async(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.RetJugador2Response> RetJugador2Async() {
            EDDS.ServiceRef.RetJugador2Request inValue = new EDDS.ServiceRef.RetJugador2Request();
            inValue.Body = new EDDS.ServiceRef.RetJugador2RequestBody();
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).RetJugador2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.RetTamanoXResponse EDDS.ServiceRef.ServicioWebSoap.RetTamanoX(EDDS.ServiceRef.RetTamanoXRequest request) {
            return base.Channel.RetTamanoX(request);
        }
        
        public string RetTamanoX() {
            EDDS.ServiceRef.RetTamanoXRequest inValue = new EDDS.ServiceRef.RetTamanoXRequest();
            inValue.Body = new EDDS.ServiceRef.RetTamanoXRequestBody();
            EDDS.ServiceRef.RetTamanoXResponse retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).RetTamanoX(inValue);
            return retVal.Body.RetTamanoXResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.RetTamanoXResponse> EDDS.ServiceRef.ServicioWebSoap.RetTamanoXAsync(EDDS.ServiceRef.RetTamanoXRequest request) {
            return base.Channel.RetTamanoXAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.RetTamanoXResponse> RetTamanoXAsync() {
            EDDS.ServiceRef.RetTamanoXRequest inValue = new EDDS.ServiceRef.RetTamanoXRequest();
            inValue.Body = new EDDS.ServiceRef.RetTamanoXRequestBody();
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).RetTamanoXAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.RetTamanoYResponse EDDS.ServiceRef.ServicioWebSoap.RetTamanoY(EDDS.ServiceRef.RetTamanoYRequest request) {
            return base.Channel.RetTamanoY(request);
        }
        
        public string RetTamanoY() {
            EDDS.ServiceRef.RetTamanoYRequest inValue = new EDDS.ServiceRef.RetTamanoYRequest();
            inValue.Body = new EDDS.ServiceRef.RetTamanoYRequestBody();
            EDDS.ServiceRef.RetTamanoYResponse retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).RetTamanoY(inValue);
            return retVal.Body.RetTamanoYResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.RetTamanoYResponse> EDDS.ServiceRef.ServicioWebSoap.RetTamanoYAsync(EDDS.ServiceRef.RetTamanoYRequest request) {
            return base.Channel.RetTamanoYAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.RetTamanoYResponse> RetTamanoYAsync() {
            EDDS.ServiceRef.RetTamanoYRequest inValue = new EDDS.ServiceRef.RetTamanoYRequest();
            inValue.Body = new EDDS.ServiceRef.RetTamanoYRequestBody();
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).RetTamanoYAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.RetTipoResponse EDDS.ServiceRef.ServicioWebSoap.RetTipo(EDDS.ServiceRef.RetTipoRequest request) {
            return base.Channel.RetTipo(request);
        }
        
        public string RetTipo() {
            EDDS.ServiceRef.RetTipoRequest inValue = new EDDS.ServiceRef.RetTipoRequest();
            inValue.Body = new EDDS.ServiceRef.RetTipoRequestBody();
            EDDS.ServiceRef.RetTipoResponse retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).RetTipo(inValue);
            return retVal.Body.RetTipoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.RetTipoResponse> EDDS.ServiceRef.ServicioWebSoap.RetTipoAsync(EDDS.ServiceRef.RetTipoRequest request) {
            return base.Channel.RetTipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.RetTipoResponse> RetTipoAsync() {
            EDDS.ServiceRef.RetTipoRequest inValue = new EDDS.ServiceRef.RetTipoRequest();
            inValue.Body = new EDDS.ServiceRef.RetTipoRequestBody();
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).RetTipoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.RetTiempoResponse EDDS.ServiceRef.ServicioWebSoap.RetTiempo(EDDS.ServiceRef.RetTiempoRequest request) {
            return base.Channel.RetTiempo(request);
        }
        
        public string RetTiempo() {
            EDDS.ServiceRef.RetTiempoRequest inValue = new EDDS.ServiceRef.RetTiempoRequest();
            inValue.Body = new EDDS.ServiceRef.RetTiempoRequestBody();
            EDDS.ServiceRef.RetTiempoResponse retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).RetTiempo(inValue);
            return retVal.Body.RetTiempoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.RetTiempoResponse> EDDS.ServiceRef.ServicioWebSoap.RetTiempoAsync(EDDS.ServiceRef.RetTiempoRequest request) {
            return base.Channel.RetTiempoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.RetTiempoResponse> RetTiempoAsync() {
            EDDS.ServiceRef.RetTiempoRequest inValue = new EDDS.ServiceRef.RetTiempoRequest();
            inValue.Body = new EDDS.ServiceRef.RetTiempoRequestBody();
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).RetTiempoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.HelloWorldResponse EDDS.ServiceRef.ServicioWebSoap.HelloWorld(EDDS.ServiceRef.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            EDDS.ServiceRef.HelloWorldRequest inValue = new EDDS.ServiceRef.HelloWorldRequest();
            inValue.Body = new EDDS.ServiceRef.HelloWorldRequestBody();
            EDDS.ServiceRef.HelloWorldResponse retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.HelloWorldResponse> EDDS.ServiceRef.ServicioWebSoap.HelloWorldAsync(EDDS.ServiceRef.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.HelloWorldResponse> HelloWorldAsync() {
            EDDS.ServiceRef.HelloWorldRequest inValue = new EDDS.ServiceRef.HelloWorldRequest();
            inValue.Body = new EDDS.ServiceRef.HelloWorldRequestBody();
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.InsercionMasivaArbolResponse EDDS.ServiceRef.ServicioWebSoap.InsercionMasivaArbol(EDDS.ServiceRef.InsercionMasivaArbolRequest request) {
            return base.Channel.InsercionMasivaArbol(request);
        }
        
        public void InsercionMasivaArbol(string Us, string Cont, string Corr, int Logi) {
            EDDS.ServiceRef.InsercionMasivaArbolRequest inValue = new EDDS.ServiceRef.InsercionMasivaArbolRequest();
            inValue.Body = new EDDS.ServiceRef.InsercionMasivaArbolRequestBody();
            inValue.Body.Us = Us;
            inValue.Body.Cont = Cont;
            inValue.Body.Corr = Corr;
            inValue.Body.Logi = Logi;
            EDDS.ServiceRef.InsercionMasivaArbolResponse retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).InsercionMasivaArbol(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.InsercionMasivaArbolResponse> EDDS.ServiceRef.ServicioWebSoap.InsercionMasivaArbolAsync(EDDS.ServiceRef.InsercionMasivaArbolRequest request) {
            return base.Channel.InsercionMasivaArbolAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.InsercionMasivaArbolResponse> InsercionMasivaArbolAsync(string Us, string Cont, string Corr, int Logi) {
            EDDS.ServiceRef.InsercionMasivaArbolRequest inValue = new EDDS.ServiceRef.InsercionMasivaArbolRequest();
            inValue.Body = new EDDS.ServiceRef.InsercionMasivaArbolRequestBody();
            inValue.Body.Us = Us;
            inValue.Body.Cont = Cont;
            inValue.Body.Corr = Corr;
            inValue.Body.Logi = Logi;
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).InsercionMasivaArbolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.InsercionMasivaListasDelArbolResponse EDDS.ServiceRef.ServicioWebSoap.InsercionMasivaListasDelArbol(EDDS.ServiceRef.InsercionMasivaListasDelArbolRequest request) {
            return base.Channel.InsercionMasivaListasDelArbol(request);
        }
        
        public void InsercionMasivaListasDelArbol(string UsB, string Op, int bb, int cc, int dd, int ee) {
            EDDS.ServiceRef.InsercionMasivaListasDelArbolRequest inValue = new EDDS.ServiceRef.InsercionMasivaListasDelArbolRequest();
            inValue.Body = new EDDS.ServiceRef.InsercionMasivaListasDelArbolRequestBody();
            inValue.Body.UsB = UsB;
            inValue.Body.Op = Op;
            inValue.Body.bb = bb;
            inValue.Body.cc = cc;
            inValue.Body.dd = dd;
            inValue.Body.ee = ee;
            EDDS.ServiceRef.InsercionMasivaListasDelArbolResponse retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).InsercionMasivaListasDelArbol(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.InsercionMasivaListasDelArbolResponse> EDDS.ServiceRef.ServicioWebSoap.InsercionMasivaListasDelArbolAsync(EDDS.ServiceRef.InsercionMasivaListasDelArbolRequest request) {
            return base.Channel.InsercionMasivaListasDelArbolAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.InsercionMasivaListasDelArbolResponse> InsercionMasivaListasDelArbolAsync(string UsB, string Op, int bb, int cc, int dd, int ee) {
            EDDS.ServiceRef.InsercionMasivaListasDelArbolRequest inValue = new EDDS.ServiceRef.InsercionMasivaListasDelArbolRequest();
            inValue.Body = new EDDS.ServiceRef.InsercionMasivaListasDelArbolRequestBody();
            inValue.Body.UsB = UsB;
            inValue.Body.Op = Op;
            inValue.Body.bb = bb;
            inValue.Body.cc = cc;
            inValue.Body.dd = dd;
            inValue.Body.ee = ee;
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).InsercionMasivaListasDelArbolAsync(inValue);
        }
        
        public void Pintar() {
            base.Channel.Pintar();
        }
        
        public System.Threading.Tasks.Task PintarAsync() {
            return base.Channel.PintarAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.EliminarEnArbolResponse EDDS.ServiceRef.ServicioWebSoap.EliminarEnArbol(EDDS.ServiceRef.EliminarEnArbolRequest request) {
            return base.Channel.EliminarEnArbol(request);
        }
        
        public void EliminarEnArbol(string nickn) {
            EDDS.ServiceRef.EliminarEnArbolRequest inValue = new EDDS.ServiceRef.EliminarEnArbolRequest();
            inValue.Body = new EDDS.ServiceRef.EliminarEnArbolRequestBody();
            inValue.Body.nickn = nickn;
            EDDS.ServiceRef.EliminarEnArbolResponse retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).EliminarEnArbol(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.EliminarEnArbolResponse> EDDS.ServiceRef.ServicioWebSoap.EliminarEnArbolAsync(EDDS.ServiceRef.EliminarEnArbolRequest request) {
            return base.Channel.EliminarEnArbolAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.EliminarEnArbolResponse> EliminarEnArbolAsync(string nickn) {
            EDDS.ServiceRef.EliminarEnArbolRequest inValue = new EDDS.ServiceRef.EliminarEnArbolRequest();
            inValue.Body = new EDDS.ServiceRef.EliminarEnArbolRequestBody();
            inValue.Body.nickn = nickn;
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).EliminarEnArbolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.ModificarEnArbolResponse EDDS.ServiceRef.ServicioWebSoap.ModificarEnArbol(EDDS.ServiceRef.ModificarEnArbolRequest request) {
            return base.Channel.ModificarEnArbol(request);
        }
        
        public void ModificarEnArbol(string Ant, string Nick, string Pass, string Mail, int Log) {
            EDDS.ServiceRef.ModificarEnArbolRequest inValue = new EDDS.ServiceRef.ModificarEnArbolRequest();
            inValue.Body = new EDDS.ServiceRef.ModificarEnArbolRequestBody();
            inValue.Body.Ant = Ant;
            inValue.Body.Nick = Nick;
            inValue.Body.Pass = Pass;
            inValue.Body.Mail = Mail;
            inValue.Body.Log = Log;
            EDDS.ServiceRef.ModificarEnArbolResponse retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).ModificarEnArbol(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.ModificarEnArbolResponse> EDDS.ServiceRef.ServicioWebSoap.ModificarEnArbolAsync(EDDS.ServiceRef.ModificarEnArbolRequest request) {
            return base.Channel.ModificarEnArbolAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.ModificarEnArbolResponse> ModificarEnArbolAsync(string Ant, string Nick, string Pass, string Mail, int Log) {
            EDDS.ServiceRef.ModificarEnArbolRequest inValue = new EDDS.ServiceRef.ModificarEnArbolRequest();
            inValue.Body = new EDDS.ServiceRef.ModificarEnArbolRequestBody();
            inValue.Body.Ant = Ant;
            inValue.Body.Nick = Nick;
            inValue.Body.Pass = Pass;
            inValue.Body.Mail = Mail;
            inValue.Body.Log = Log;
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).ModificarEnArbolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.IncertarEnMatrizLiveResponse EDDS.ServiceRef.ServicioWebSoap.IncertarEnMatrizLive(EDDS.ServiceRef.IncertarEnMatrizLiveRequest request) {
            return base.Channel.IncertarEnMatrizLive(request);
        }
        
        public void IncertarEnMatrizLive(string jug, int col, int fil, string uni, int des) {
            EDDS.ServiceRef.IncertarEnMatrizLiveRequest inValue = new EDDS.ServiceRef.IncertarEnMatrizLiveRequest();
            inValue.Body = new EDDS.ServiceRef.IncertarEnMatrizLiveRequestBody();
            inValue.Body.jug = jug;
            inValue.Body.col = col;
            inValue.Body.fil = fil;
            inValue.Body.uni = uni;
            inValue.Body.des = des;
            EDDS.ServiceRef.IncertarEnMatrizLiveResponse retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).IncertarEnMatrizLive(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.IncertarEnMatrizLiveResponse> EDDS.ServiceRef.ServicioWebSoap.IncertarEnMatrizLiveAsync(EDDS.ServiceRef.IncertarEnMatrizLiveRequest request) {
            return base.Channel.IncertarEnMatrizLiveAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.IncertarEnMatrizLiveResponse> IncertarEnMatrizLiveAsync(string jug, int col, int fil, string uni, int des) {
            EDDS.ServiceRef.IncertarEnMatrizLiveRequest inValue = new EDDS.ServiceRef.IncertarEnMatrizLiveRequest();
            inValue.Body = new EDDS.ServiceRef.IncertarEnMatrizLiveRequestBody();
            inValue.Body.jug = jug;
            inValue.Body.col = col;
            inValue.Body.fil = fil;
            inValue.Body.uni = uni;
            inValue.Body.des = des;
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).IncertarEnMatrizLiveAsync(inValue);
        }
        
        public void PintarMSobrevivientes() {
            base.Channel.PintarMSobrevivientes();
        }
        
        public System.Threading.Tasks.Task PintarMSobrevivientesAsync() {
            return base.Channel.PintarMSobrevivientesAsync();
        }
        
        public void PintarMDestruidas() {
            base.Channel.PintarMDestruidas();
        }
        
        public System.Threading.Tasks.Task PintarMDestruidasAsync() {
            return base.Channel.PintarMDestruidasAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.EliminarEnMatrizResponse EDDS.ServiceRef.ServicioWebSoap.EliminarEnMatriz(EDDS.ServiceRef.EliminarEnMatrizRequest request) {
            return base.Channel.EliminarEnMatriz(request);
        }
        
        public void EliminarEnMatriz(string jug, int col, int fil, string uni, int niv) {
            EDDS.ServiceRef.EliminarEnMatrizRequest inValue = new EDDS.ServiceRef.EliminarEnMatrizRequest();
            inValue.Body = new EDDS.ServiceRef.EliminarEnMatrizRequestBody();
            inValue.Body.jug = jug;
            inValue.Body.col = col;
            inValue.Body.fil = fil;
            inValue.Body.uni = uni;
            inValue.Body.niv = niv;
            EDDS.ServiceRef.EliminarEnMatrizResponse retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).EliminarEnMatriz(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.EliminarEnMatrizResponse> EDDS.ServiceRef.ServicioWebSoap.EliminarEnMatrizAsync(EDDS.ServiceRef.EliminarEnMatrizRequest request) {
            return base.Channel.EliminarEnMatrizAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.EliminarEnMatrizResponse> EliminarEnMatrizAsync(string jug, int col, int fil, string uni, int niv) {
            EDDS.ServiceRef.EliminarEnMatrizRequest inValue = new EDDS.ServiceRef.EliminarEnMatrizRequest();
            inValue.Body = new EDDS.ServiceRef.EliminarEnMatrizRequestBody();
            inValue.Body.jug = jug;
            inValue.Body.col = col;
            inValue.Body.fil = fil;
            inValue.Body.uni = uni;
            inValue.Body.niv = niv;
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).EliminarEnMatrizAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EDDS.ServiceRef.CopiarImagenesResponse EDDS.ServiceRef.ServicioWebSoap.CopiarImagenes(EDDS.ServiceRef.CopiarImagenesRequest request) {
            return base.Channel.CopiarImagenes(request);
        }
        
        public void CopiarImagenes(string r) {
            EDDS.ServiceRef.CopiarImagenesRequest inValue = new EDDS.ServiceRef.CopiarImagenesRequest();
            inValue.Body = new EDDS.ServiceRef.CopiarImagenesRequestBody();
            inValue.Body.r = r;
            EDDS.ServiceRef.CopiarImagenesResponse retVal = ((EDDS.ServiceRef.ServicioWebSoap)(this)).CopiarImagenes(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EDDS.ServiceRef.CopiarImagenesResponse> EDDS.ServiceRef.ServicioWebSoap.CopiarImagenesAsync(EDDS.ServiceRef.CopiarImagenesRequest request) {
            return base.Channel.CopiarImagenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EDDS.ServiceRef.CopiarImagenesResponse> CopiarImagenesAsync(string r) {
            EDDS.ServiceRef.CopiarImagenesRequest inValue = new EDDS.ServiceRef.CopiarImagenesRequest();
            inValue.Body = new EDDS.ServiceRef.CopiarImagenesRequestBody();
            inValue.Body.r = r;
            return ((EDDS.ServiceRef.ServicioWebSoap)(this)).CopiarImagenesAsync(inValue);
        }
    }
}
